[mypy]
python_version = 3.10
strict = true
warn_unused_ignores = true
disallow_any_unimported = true
files = src/upgrade_pyutils, src/truenas-initrd.py

[mypy-tests.*]
disallow_untyped_defs = false
disallow_incomplete_defs = false
check_untyped_defs = true
